# Generated by Django 5.0 on 2024-11-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
